CREATE DATABASE IF NOT EXISTS storemanager;
USE storemanager;

INSERT INTO ufs (initials, name) VALUES ('AC', 'Acre');
INSERT INTO ufs (initials, name) VALUES ('AL', 'Alagoas');
INSERT INTO ufs (initials, name) VALUES ('AP', 'Amapá');
INSERT INTO ufs (initials, name) VALUES ('AM', 'Amazonas');
INSERT INTO ufs (initials, name) VALUES ('BA', 'Bahia');
INSERT INTO ufs (initials, name) VALUES ('CE', 'Ceará');
INSERT INTO ufs (initials, name) VALUES ('DF', 'Distrito Federal');
INSERT INTO ufs (initials, name) VALUES ('ES', 'Espirito Santo');
INSERT INTO ufs (initials, name) VALUES ('GO', 'Goiás');
INSERT INTO ufs (initials, name) VALUES ('MA', 'Maranhão');
INSERT INTO ufs (initials, name) VALUES ('MT', 'Mato Grosso');
INSERT INTO ufs (initials, name) VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO ufs (initials, name) VALUES ('MG', 'Minas Gerais');
INSERT INTO ufs (initials, name) VALUES ('PA', 'Pará');
INSERT INTO ufs (initials, name) VALUES ('PB', 'Paraíba');
INSERT INTO ufs (initials, name) VALUES ('PR', 'Paraná');
INSERT INTO ufs (initials, name) VALUES ('PE', 'Pernambuco');
INSERT INTO ufs (initials, name) VALUES ('PI', 'Piauí');
INSERT INTO ufs (initials, name) VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO ufs (initials, name) VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO ufs (initials, name) VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO ufs (initials, name) VALUES ('RO', 'Rondônia');
INSERT INTO ufs (initials, name) VALUES ('RR', 'Roraima');
INSERT INTO ufs (initials, name) VALUES ('SC', 'Santa Catarina');
INSERT INTO ufs (initials, name) VALUES ('SP', 'São Paulo');
INSERT INTO ufs (initials, name) VALUES ('SE', 'Sergipe');
INSERT INTO ufs (initials, name) VALUES ('TO', 'Tocantins');
insert into users (name, username, password, is_admin) values ('Administrador', 'admin', 'admin', 1);
insert into users (name, username, password, is_admin) values ('Mateus', 'mateuslineri', 'alface', 0);